spring.application.name=demoCrudEcommerceM6
spring.mvc.locale=es-CL

#BASE DE DATOS THYMELEAF
spring.datasource.url=jdbc:mysql://localhost:3306/crud_ecommerce_m6
spring.datasource.username=root
spring.datasource.password=Kym.101419
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# NO GUARDE CACHE MEMORIA EN PAGINA
spring.thymeleaf.cache=false

# Ruta en tu PC donde se guardarán las fotos (Crea esta carpeta manualmente)
app.upload.path=C:/magical-alliance-uploads

# Permitir que Spring sirva archivos externos
spring.mvc.static-path-pattern=/**

# Debug para ver posibles fallos en consola
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.security=DEBUG